import { StyleSheet } from 'react-native';

import { colors } from './colors';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.black,
  },
  screenSafe: {
    flex: 1,
    backgroundColor: colors.black,
  },
  keyboard: {
    flex: 1,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  authScreen: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 22,
    gap: 18,
    backgroundColor: colors.black,
  },
  authHero: {
    gap: 16,
    backgroundColor: colors.surface,
    borderColor: colors.critical,
    borderWidth: 1,
    borderRadius: 32,
    padding: 24,
    overflow: 'hidden',
  },
  meshMark: {
    height: 112,
    borderRadius: 28,
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.border,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  meshNodeLarge: {
    width: 54,
    height: 54,
    borderRadius: 999,
    backgroundColor: colors.critical,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#ff8a8a',
    borderWidth: 2,
  },
  meshNodeText: {
    color: colors.text,
    fontWeight: '900',
    fontSize: 20,
  },
  meshNodeSmallRow: {
    position: 'absolute',
    left: 24,
    right: 24,
    top: 42,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  meshNodeSmall: {
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: colors.surfaceLift,
    borderColor: colors.meshBlue,
    borderWidth: 2,
  },
  meshLine: {
    position: 'absolute',
    left: 42,
    right: 42,
    height: 2,
    backgroundColor: colors.border,
  },
  authStatusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  authStatusPill: {
    color: colors.text,
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    fontSize: 11,
    fontWeight: '800',
  },
  appShell: {
    flex: 1,
    backgroundColor: colors.black,
  },
  content: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
  },
  eyebrow: {
    color: colors.critical,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  title: {
    color: colors.text,
    fontSize: 25,
    fontWeight: '900',
    marginTop: 4,
  },
  heroTitle: {
    color: colors.text,
    fontSize: 42,
    lineHeight: 46,
    fontWeight: '900',
  },
  heroCopy: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 24,
  },
  headerPill: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
  },
  headerPillNumber: {
    color: colors.low,
    fontSize: 18,
    fontWeight: '900',
  },
  headerPillText: {
    color: colors.muted,
    fontSize: 11,
  },
  roleRow: {
    gap: 10,
  },
  roleButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 24,
    padding: 16,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  roleButtonActive: {
    borderColor: colors.critical,
    backgroundColor: colors.criticalSoft,
  },
  roleAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
  },
  roleText: {
    color: colors.text,
    fontWeight: '900',
    fontSize: 17,
  },
  roleTextActive: {
    color: colors.text,
  },
  roleSubtext: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 5,
  },
  authCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  screen: {
    padding: 16,
    gap: 16,
    paddingBottom: 112,
  },
  homeHero: {
    gap: 8,
    paddingHorizontal: 4,
  },
  homeTitle: {
    color: colors.text,
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '900',
  },
  dashboardHero: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 28,
    padding: 18,
    gap: 8,
  },
  dashboardTitle: {
    color: colors.text,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    padding: 18,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '900',
  },
  cardCopy: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  input: {
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 18,
    color: colors.text,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
  },
  storyInput: {
    minHeight: 106,
    textAlignVertical: 'top',
  },
  primaryButton: {
    backgroundColor: colors.critical,
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
  },
  primaryButtonCompact: {
    flex: 1,
    backgroundColor: colors.critical,
    borderRadius: 18,
    paddingVertical: 15,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 18,
    paddingVertical: 15,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: colors.text,
    fontWeight: '800',
  },
  sosButton: {
    minHeight: 184,
    backgroundColor: colors.critical,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.critical,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 10,
  },
  sosOrbit: {
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 32,
  },
  orbitTopRow: {
    width: '78%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  orbitMiddleRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orbitBottomRow: {
    width: '72%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  orbitChip: {
    minWidth: 86,
    minHeight: 48,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.border,
    borderWidth: 1,
  },
  orbitChipActive: {
    backgroundColor: colors.criticalSoft,
    borderColor: colors.critical,
  },
  orbitChipText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  orbitChipTextActive: {
    color: colors.text,
  },
  sosRoundButton: {
    width: 172,
    height: 172,
    borderRadius: 999,
    backgroundColor: colors.critical,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#ff6b6b',
    borderWidth: 2,
    shadowColor: colors.critical,
    shadowOpacity: 0.4,
    shadowRadius: 18,
    elevation: 12,
  },
  sosRoundText: {
    color: colors.text,
    fontSize: 52,
    lineHeight: 58,
    fontWeight: '900',
    letterSpacing: 2,
  },
  sosRoundSubtext: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
    opacity: 0.9,
    textTransform: 'uppercase',
  },
  selectedReasonBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  selectedReasonLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  selectedReasonValue: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '900',
  },
  sosText: {
    color: colors.text,
    fontSize: 70,
    lineHeight: 76,
    fontWeight: '900',
    letterSpacing: 4,
  },
  sosSubtext: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    opacity: 0.9,
  },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
  },
  chipActive: {
    backgroundColor: colors.text,
    borderColor: colors.text,
  },
  chipText: {
    color: colors.muted,
    fontWeight: '800',
  },
  chipTextActive: {
    color: colors.black,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  actionRowWrap: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  signalCard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: 24,
    padding: 14,
    paddingLeft: 18,
    gap: 8,
    borderColor: colors.border,
    borderWidth: 1,
    overflow: 'hidden',
  },
  signalPriorityRail: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
  },
  signalTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  priorityDot: {
    width: 12,
    height: 12,
    borderRadius: 99,
    marginTop: 5,
  },
  signalTitle: {
    flex: 1,
    color: colors.text,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '900',
  },
  signalMeta: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  signalBody: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 21,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusPill: {
    overflow: 'hidden',
    color: colors.black,
    backgroundColor: colors.low,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 10,
    fontWeight: '900',
  },
  assignmentPill: {
    alignSelf: 'flex-start',
    color: colors.black,
    backgroundColor: colors.authorityAmber,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 11,
    fontWeight: '900',
  },
  locationPanel: {
    backgroundColor: colors.meshSoft,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 10,
    gap: 4,
  },
  routeText: {
    flex: 1,
    color: colors.muted,
    fontSize: 11,
  },
  locationText: {
    color: colors.blue,
    fontSize: 12,
  },
  miniAction: {
    backgroundColor: colors.surfaceLift,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  assignAction: {
    backgroundColor: colors.authoritySoft,
    borderColor: colors.authorityAmber,
  },
  miniActionText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '900',
  },
  commandGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  metric: {
    flex: 1,
    backgroundColor: colors.surfaceSoft,
    borderRadius: 20,
    padding: 14,
    borderColor: colors.border,
    borderWidth: 1,
  },
  metricValue: {
    fontSize: 30,
    fontWeight: '900',
  },
  metricLabel: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 3,
  },
  mapFrame: {
    borderRadius: 26,
    overflow: 'hidden',
    borderColor: colors.border,
    borderWidth: 1,
  },
  emptyText: {
    color: colors.muted,
    paddingVertical: 10,
  },
  peerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderRadius: 18,
    padding: 14,
  },
  peerName: {
    color: colors.text,
    fontWeight: '900',
  },
  logLine: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 20,
  },
  settingLine: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 22,
  },
  muted: {
    color: colors.muted,
  },
  tabBar: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 18,
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#050505',
    borderRadius: 26,
    padding: 8,
    borderColor: colors.border,
    borderWidth: 1,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 18,
  },
  tabActive: {
    backgroundColor: colors.text,
  },
  tabText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  tabTextActive: {
    color: colors.black,
  },
});
