import { StyleSheet } from 'react-native';

import { colors } from './colors';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.black,
  },
  screenSafe: {
    flex: 1,
    backgroundColor: colors.black,
  },
  keyboard: {
    flex: 1,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  authScreen: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 22,
    gap: 18,
    backgroundColor: colors.black,
  },
  appShell: {
    flex: 1,
    backgroundColor: colors.black,
  },
  content: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
  },
  eyebrow: {
    color: colors.critical,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  title: {
    color: colors.text,
    fontSize: 25,
    fontWeight: '900',
    marginTop: 4,
  },
  heroTitle: {
    color: colors.text,
    fontSize: 39,
    lineHeight: 43,
    fontWeight: '900',
  },
  heroCopy: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 24,
  },
  headerPill: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
  },
  headerPillNumber: {
    color: colors.low,
    fontSize: 18,
    fontWeight: '900',
  },
  headerPillText: {
    color: colors.muted,
    fontSize: 11,
  },
  roleRow: {
    flexDirection: 'row',
    gap: 10,
  },
  roleButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 14,
    backgroundColor: colors.panel,
  },
  roleButtonActive: {
    borderColor: colors.critical,
    backgroundColor: '#180303',
  },
  roleText: {
    color: colors.muted,
    fontWeight: '800',
    textAlign: 'center',
  },
  roleTextActive: {
    color: colors.text,
  },
  authCard: {
    backgroundColor: colors.panel,
    borderRadius: 28,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  screen: {
    padding: 16,
    gap: 16,
    paddingBottom: 112,
  },
  card: {
    backgroundColor: colors.panel,
    borderRadius: 28,
    padding: 18,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '900',
  },
  cardCopy: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  input: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 18,
    color: colors.text,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
  },
  storyInput: {
    minHeight: 106,
    textAlignVertical: 'top',
  },
  primaryButton: {
    backgroundColor: colors.critical,
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
  },
  primaryButtonCompact: {
    flex: 1,
    backgroundColor: colors.critical,
    borderRadius: 18,
    paddingVertical: 15,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 18,
    paddingVertical: 15,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: colors.text,
    fontWeight: '800',
  },
  sosButton: {
    minHeight: 184,
    backgroundColor: colors.critical,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.critical,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 10,
  },
  sosText: {
    color: colors.text,
    fontSize: 70,
    lineHeight: 76,
    fontWeight: '900',
    letterSpacing: 4,
  },
  sosSubtext: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    opacity: 0.9,
  },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
  },
  chipActive: {
    backgroundColor: colors.text,
    borderColor: colors.text,
  },
  chipText: {
    color: colors.muted,
    fontWeight: '800',
  },
  chipTextActive: {
    color: colors.black,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  actionRowWrap: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  signalCard: {
    backgroundColor: colors.panel2,
    borderRadius: 22,
    padding: 14,
    gap: 8,
    borderColor: colors.border,
    borderWidth: 1,
  },
  signalTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  priorityDot: {
    width: 12,
    height: 12,
    borderRadius: 99,
    marginTop: 5,
  },
  signalTitle: {
    flex: 1,
    color: colors.text,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '900',
  },
  signalMeta: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  signalBody: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 21,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusPill: {
    overflow: 'hidden',
    color: colors.black,
    backgroundColor: colors.low,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 10,
    fontWeight: '900',
  },
  routeText: {
    flex: 1,
    color: colors.muted,
    fontSize: 11,
  },
  locationText: {
    color: colors.blue,
    fontSize: 12,
  },
  miniAction: {
    backgroundColor: colors.panel3,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  miniActionText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '900',
  },
  commandGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  metric: {
    flex: 1,
    backgroundColor: colors.panel2,
    borderRadius: 20,
    padding: 14,
    borderColor: colors.border,
    borderWidth: 1,
  },
  metricValue: {
    fontSize: 30,
    fontWeight: '900',
  },
  metricLabel: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 3,
  },
  mapFrame: {
    borderRadius: 26,
    overflow: 'hidden',
    borderColor: colors.border,
    borderWidth: 1,
  },
  emptyText: {
    color: colors.muted,
    paddingVertical: 10,
  },
  peerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.panel2,
    borderRadius: 18,
    padding: 14,
  },
  peerName: {
    color: colors.text,
    fontWeight: '900',
  },
  logLine: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 20,
  },
  settingLine: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 22,
  },
  muted: {
    color: colors.muted,
  },
  tabBar: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 18,
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#050505',
    borderRadius: 26,
    padding: 8,
    borderColor: colors.border,
    borderWidth: 1,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 18,
  },
  tabActive: {
    backgroundColor: colors.text,
  },
  tabText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  tabTextActive: {
    color: colors.black,
  },
});
